# Generated by Django 3.2.11 on 2022-02-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0003_rename_activation_fey_shopuser_activation_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="age",
            field=models.PositiveIntegerField(default=18, verbose_name="возраст"),
        ),
    ]
